# Generated by Django 3.2.3 on 2021-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to='image/data/')),
                ('config_data_json', models.CharField(max_length=1000, null=True)),
                ('config_load_json', models.CharField(max_length=1000, null=True)),
                ('datatype', models.CharField(default='image', max_length=10)),
                ('aif_input_file_path', models.FilePathField(null=True, path='image/data/dataframes')),
            ],
        ),
    ]
